# Generated by Django 3.2.8 on 2022-06-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_file',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.CharField(blank=True, db_column='file_id', max_length=50, null=True, verbose_name='File_Id')),
                ('file_name', models.CharField(blank=True, db_column='file_name', max_length=50, null=True, verbose_name='File_Name')),
                ('file_type', models.CharField(blank=True, db_column='file_type', max_length=50, null=True, verbose_name='File_Type')),
                ('file_size', models.TextField(blank=True, db_column='file_size', null=True, verbose_name='File_Size')),
                ('screat_key', models.TextField(blank=True, db_column='screat_key', max_length=100, null=True, verbose_name='Screat_Key')),
                ('Key', models.TextField(blank=True, db_column='key', max_length=500, null=True, verbose_name='Key')),
                ('status', models.CharField(blank=True, db_column='status', default='Pending', max_length=50, verbose_name='Status')),
                ('request_mail', models.EmailField(blank=True, db_column='request_mail', max_length=100, null=True, verbose_name='Request_Mail')),
                ('user_id', models.CharField(blank=True, db_column='user_id', max_length=50, null=True, verbose_name='User_id')),
                ('user_file', models.FileField(blank=True, db_column='user_file', upload_to='Data-User/Files/', verbose_name='User_File')),
            ],
            options={
                'db_table': 'Request_file',
            },
        ),
    ]
