# Generated by Django 3.2.8 on 2022-06-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_user', '0003_rename_user_id_request_file_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_file',
            name='owner_id',
            field=models.CharField(blank=True, db_column='owner_id', max_length=50, null=True, verbose_name='Owner_id'),
        ),
    ]
