# Generated by Django 3.2.8 on 2022-06-29 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_owner', '0004_remove_upload_file_user_id'),
        ('data_user', '0004_alter_request_file_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_file',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='request_file',
            name='owner',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_owner.data_owner_register'),
        ),
    ]
