# Generated by Django 3.2.8 on 2022-06-30 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_user', '0005_auto_20220629_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_column='user_name', max_length=50, verbose_name='User_Name')),
                ('user_email', models.EmailField(blank=True, db_column='user_email', max_length=100, null=True, verbose_name='User_Email')),
                ('user_image', models.FileField(blank=True, db_column='user_image', upload_to='User/Profile-image/', verbose_name='User_Image')),
                ('attack_file', models.FileField(blank=True, db_column='attack_file', upload_to='Attack_file/Files/', verbose_name='Attack_File')),
                ('datetime_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Attack_file',
            },
        ),
    ]
