# Generated by Django 3.2.8 on 2022-06-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_user', '0006_attack_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack_file',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attack_file',
            name='user_image',
            field=models.FileField(blank=True, db_column='user_image', upload_to='Attack_file/Profile-image/', verbose_name='User_Image'),
        ),
    ]
