# Generated by Django 3.2.8 on 2022-07-01 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_user', '0007_auto_20220630_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download_file',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(blank=True, db_column='user_email', max_length=100, null=True, verbose_name='User_Email')),
                ('file_name', models.CharField(db_column='file_name', max_length=50, verbose_name='File_Name')),
                ('file_size', models.CharField(db_column='file_size', max_length=50, verbose_name='File_Size')),
                ('datetime_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Download_file',
            },
        ),
    ]
