# Generated by Django 3.2.8 on 2022-07-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_user', '0009_data_user_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack_file',
            name='status',
            field=models.CharField(blank=True, db_column='status', default='Pending', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='attack_file',
            name='attack_file',
            field=models.CharField(blank=True, db_column='attack_file', max_length=100, null=True, verbose_name='Attack_File'),
        ),
    ]
