# Generated by Django 3.2.8 on 2022-06-28 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_file',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, db_column='user_id', max_length=50, null=True, verbose_name='User_Id')),
                ('select', models.CharField(blank=True, db_column='select', max_length=50, null=True, verbose_name='Select')),
                ('file_name', models.CharField(blank=True, db_column='file_name', max_length=50, null=True, verbose_name='File_Name')),
                ('file_type', models.CharField(blank=True, db_column='file_type', max_length=50, null=True, verbose_name='File_Type')),
                ('file_size', models.TextField(blank=True, db_column='file_size', null=True, verbose_name='File_Size')),
                ('Key', models.TextField(blank=True, db_column='key', max_length=500, null=True, verbose_name='Key')),
                ('file_data', models.TextField(blank=True, db_column='file_data', max_length=100, null=True, verbose_name='File_Data')),
                ('decription', models.TextField(blank=True, db_column='decription', max_length=50, null=True, verbose_name='Decription')),
                ('files', models.FileField(blank=True, db_column='files', upload_to='User/Files/', verbose_name='Files')),
                ('datetime_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Upload_file',
            },
        ),
    ]
