# Generated by Django 3.2.8 on 2022-06-29 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_owner', '0002_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_file',
            name='owner',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_owner.data_owner_register'),
        ),
    ]
