# Generated by Django 3.2.8 on 2022-06-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_owner', '0003_upload_file_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_file',
            name='user_id',
        ),
    ]
